### ISSUE TITLE
Calabash in directory with spaces in path

### ISSUE THREAD

**Issue by mabromuela88** [transpect/xml2tex#11]
Why do calabash fails when there is a space in its directory path where it resides? It throws 'Could not find or load main class' and ClassNotFoundException.

**Comment by gimsieke** [comment]
How do you invoke it? There are some related issues, for example https://github.com/transpect/docx2tex/issues/81, but they seem to be solved already.

**Comment by mabromuela88** [comment]
I invoke it through an automating script written in Java. I use Windows OS hence run the calabash.bat file. Here is the code snippet:

```
ProcessBuilder pb1 = new ProcessBuilder("cmd.exe", "/c", "calabash\\calabash.bat -o result=\"/" + outputTexPath + ".tex\" -i source=\"/" + inputFile + ".xml\" -i conf=\"/" + confFile + ".xml\" xml2tex/xpl/xml2tex.xpl");
pb1.redirectErrorStream(true);
```

**Comment by gimsieke** [comment]
I can reproduce it with calabash.bat in a space-containing directory

**Comment by gimsieke** [comment]
Which branch of https://github.com/transpect/calabash-frontend/ are you using? I see that the necessary fix, that is, quotation marks around `%classpath%`, is already present in https://github.com/transpect/calabash-frontend/blob/master/calabash.bat#L42

**Comment by mabromuela88** [comment]
I am using calabash.bat from the one I cloned from xml2tex repo

**Comment by gimsieke** [comment]
xml2tex doesn’t ship with calabash, [docx2tex](https://github.com/transpect/docx2tex) does. Well, you can edit whatever calabash.bat that you have there and replace `%classpath%` with `"%classpath%"`.

**Comment by mabromuela88** [comment]
If I change `%classpath%` with `"%classpath%"` I get

```
Only options can occur on the command line after the pipeline document.
Usage: com.xmlcalabash.drivers.Main [switches/options] [pipeline.xpl] [options]
   or: com.xmlcalabash.drivers.Main [switches/options] { [inputs/parameters] ste
p [options] }+
```

**Comment by gimsieke** [comment]
Hmm. Maybe you need to insert more `"` characters. Try it in the following line (line 31 in the calabash.bat that I’m looking at):

```
@set config="%scriptdir%extensions/transpect/transpect-config.xml"
```

**Comment by mabromuela88** [comment]
It worked!!!

**Comment by gimsieke** [comment]
Excellent. Thank you for reporting it.
