### ISSUE TITLE
Always escape % in \href

### ISSUE THREAD

**Issue by roberthechtletex** [transpect/xml2tex#12]
Please escape all `%` in `\href` with `\` (backslash) – not only in the second argument, but also _in the first argument_.

Reason: There occurs a fatal TeX error when compiling un-escaped `%` in `\href` _in a `\footnote`._

**Comment by mkraetke** [comment]
docx2tex already escapes control characters such as `%` in `\href`. I've tested this with a small sample and the `%` characters were properly escaped:
```tex
\begin{document}
Fußnote\footnote{\href{https://www.google.com/search?q=schei\%C3\%9Fe}{Hyperlink}}
\end{document}
```
Maybe you used the output from a transpect workflow that overrides the default configuration of docx2tex?

**Comment by mkraetke** [comment]
Was not clear that the BITS config was used. Now this issue should be resolved.
