### ISSUE TITLE
Verbatim texts in converted XML

### ISSUE THREAD

**Issue by mabromuela88** [transpect/xml2tex#9]
Is there a tag to enclose texts and symbols exactly the way it should be. Example: `<plain>\clearpage</plain>` should just write `\clearpage` in tex file without any conversion i.e., `\` is not being written as `\textbackslash`. This is important when I want to do some TikZ drawings in XML, just to leave the code the way it is.

**Comment by mabromuela88** [comment]
Actually how do I escape characters?

**Comment by gimsieke** [comment]
Do you have a sample input document? 

And how do you invoke xml2tex?

Maybe I can show you how to tweak the configuration so that there is no `\textbackslash` in certain contexts.

The main template that is responsible for escaping seems to be [this](https://github.com/transpect/xml2tex/blob/master/xsl/xml2tex.xsl#L83). But it is not an immediate XSLT template. The actual XSLT stylesheet will be generated from these templates and from processing the configuration file.

Your second question about escaping: Which characters do you want to escape in which contexts? Isn’t there already enough escaping going on?

**Comment by mabromuela88** [comment]
```
<?xml version="1.0" encoding="UTF-8"?>
<hub xmlns="http://docbook.org/ns/docbook" version="5.0">
<para>\textbf{BOLD}</para>
</hub>
```

Suppose for whatever reason I want to write `\textbf{BOLD}` to the output tex file. So what happens in the output is that `\` gets replaced by `\textbackslash`, `{` gets replaced by `\{` and '}' gets replaced by `\}`. So by escape, I mean just to be the way they are, `\` remains `\` and so on.

**Comment by mabromuela88** [comment]
by invoking, isn't it generally done through calabash with some config file and an xpl file? I actually modified a bit on section headings using `conf-hubcssa.xml`.

**Comment by gimsieke** [comment]
It is not a good idea to change an existing configuration. You might get a conflict if someone else commits something incompatible, and you won’t be able to store your changes to revision control.

Please use the import mechanism in order to override configuration settings. For your problem, I overrode the XSLT template that matches `text()` in mode `escape-bad-chars`, it doesn’t stem from the configuration, but from xml2tex.xsl itself (the one I linked to in a previous comment).

```xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-model href="http://transpect.io/xml2tex/schema/xml2tex.rng" 
  type="application/xml" schematypens="http://relaxng.org/ns/structure/1.0"?>
<?xml-model href="http://transpect.io/xml2tex/schema/xml2tex.rng" 
  type="application/xml" schematypens="http://purl.oclc.org/dsdl/schematron"?>
<set xmlns="http://transpect.io/xml2tex"  
     xmlns:tr="http://transpect.io"
     xmlns:xsl="http://www.w3.org/1999/XSL/Transform">
  
  <import href="http://transpect.io/xml2tex/example/conf-hubcssa.xml"/>
  
  <xsl:template match="dbk:para/text()" mode="escape-bad-chars">
    <xsl:value-of select="."/>
  </xsl:template>

</set>
```

Invocation: 

```bash
calabash/calabash.sh -i source=xml2tex/test-doc.xml -i conf=xml2tex/test-conf.xml xml2tex/xpl/xml2tex.xpl
```

(provided that your example is in xml2tex/test-doc.xml and the configuration is in xml2tex/test-conf.xml).

Output:

```tex
…
\begin{document}

\textbf{BOLD}



\end{document}
```

**Comment by mabromuela88** [comment]
That's okay, I have copied the config file in my local PC, so nothing is changed in the repo, just so I can tinker with it locally. I am very grateful to the contributors like you for this project. Cheers!

**Comment by gimsieke** [comment]
I’m not afraid of you changing files in the Github repo (you don’t have commit permissions). It’s rather that changes that you apply to your checked-out copy have no chance of being made persistent, and are in danger of getting run over if we commit something to conf-hubcssa.xml and you subsequently update that file. It’s just bad practice to locally change library files.

**Comment by gimsieke** [comment]
In the course of preparing and testing the example, I noticed this message:

> Message: [WARNING]: Configuration is not valid with respect to the schema. Please validate your configuration file with schema/xml2tex.rng.

This is not your fault. There was an error in conf-hubcssa.xml that I fixed. You can git pull or svn up the repo in order to have that fixed in your local copy, too.

**Comment by mabromuela88** [comment]
Ah! I also have been thinking about that too. I did link to the right directory for RNG Schema. I tried from url as well as from my local file. I got error in both ways. Thanks for fixing!

**Comment by gimsieke** [comment]
Colleagues suggested that you may also use processing instructions for verbatim TeX code, like this:

```xml
<para><?passthru \textit{ITALIC}

\begin{array}
  …
\end{array}
  ?></para>
```

Put this in your configuration:

```xml
  <xsl:template match="processing-instruction(passthru)" mode="xml2tex">
    <xsl:value-of select="."/>
  </xsl:template>
```

Output:

```tex
\textit{ITALIC}

\begin{array}
  …
\end{array}
```

Thinking about it, I put it into xml2tex.xsl proper so you only need to update it and can use `<?passthru \some\macro?>` in your XML.

**Comment by mabromuela88** [comment]
Hi! the `passthru` implementation worked nicely. Now I just need one more piece of information. Could you explain how the following line works or is implemented in input xml?


```
  <template context="dbk:para[@css:text-align='center'
                              or exists(key('style', @role)[@css:text-align eq 'center'])]
                             [not(parent::*[local-name() = ('entry', 'th', 'td')])]">
    <rule name="center" type="env" break-after="2">
      <text/>
    </rule>
  </template>
```

I wanted to put a group of texts in the center environment. Keeping in line with <para role="...."> with `dbk` namespace declared in the beginning of the input file, I thought `<para css:text-align='center'>texts</para>` would work. But it throws error "The prefix 'css' for attribute "css:text-align" associated with an element type "para" is not found." What am I missing?

**Comment by gimsieke** [comment]
If you use namespaced attributes in your XML input, you need to declare these namespaces. The `css` prefix is expected to be bound to `http://www.w3.org/1996/css`, so you need to attach `xmlns:css="http://www.w3.org/1996/css"` to your top-level element or  to the `para`, that is, `<para xmlns:css="http://www.w3.org/1996/css" css:text-align='center'>texts</para>`.

Maybe also add the line `<ns prefix="css" uri="http://www.w3.org/1996/css"/>` as found in [conf-bits.xml](https://github.com/transpect/xml2tex/blob/master/example/conf-bits.xml#L8) to your configuration if needed. But maybe it isn’t necessary.
